apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-task
  labels:
    {{- include "psykl.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.serviceTask.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "psykl.serviceTask.selectorLabels" . | nindent 4 }}
