apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-client
  labels:
    {{- include "psykl.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.webClient.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "psykl.webClient.selectorLabels" . | nindent 4 }}
